FROM caddy:2.8-builder AS builder

RUN xcaddy build \
  --with github.com/caddyserver/replace-response \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/WeidiDeng/caddy-cloudflare-ip \
  --with github.com/mholt/caddy-l4 \
  --with github.com/abiosoft/caddy-exec

FROM caddy:2.8

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
